### ISSUE TITLE
TrimStrings truncates data

### ISSUE THREAD

**Issue by mzimmerman** [kshedden/datareader#1]
I often use the stattocsv command line utility to work with data using the GNU utilities and I noticed that some of my columns with addresses, e.g., "50 E. Main St" only came out as "50".

I then wrote my own frontend using your library to spit out as CSV and it didn't have that issue.

Debugging some, I found it was the TrimStrings bool value causing the problem but I didn't debug further.

**Comment by kshedden** [comment]
Thanks for the report.  I think I have fixed this now.  Can you let me know?

**Comment by mzimmerman** [comment]
Looks good!  Thanks
