### ISSUE TITLE
Writer?

### ISSUE THREAD

**Issue by jontonsoup** [kshedden/datareader#2]
Does this library only read stata.dta files? Is it possible to write them? 

Thanks!

**Comment by kshedden** [comment]
Sorry, only reading is implemented.

On Tue, May 23, 2017 at 4:41 PM, Jonathan Friedman <notifications@github.com

**Comment by maplechori** [comment]
Is the Series type going to be extended to hold information such as labels in Stata?

**Comment by kshedden** [comment]
I think what you want is available through some exported fields of the StataReader struct, e.g.:

https://github.com/kshedden/datareader/blob/master/stata_reader.go#L85

If something important is not accessible let me know.

**Comment by maplechori** [comment]
Yeah I can see you are reading the labels. But I don't see them being stored in the Series data type.
