### ISSUE TITLE
First rows of Stata file are repeatedly re-read on each call to Read()

### ISSUE THREAD

**Issue by duncanharris** [kshedden/datareader#7]
`Seek(,0)` happens on every read so first `rows` of file are repeatedly re-read on each call to `Read()`
https://github.com/kshedden/datareader/blob/8c617eeda35976f2a27fc979ef1590acc66c5a06/stata_reader.go#L843

**Comment by kshedden** [comment]
Thanks, I think I have fixed this now.  If further issues with this let me know.
