### ISSUE TITLE
Reader does not handle column labels. 

### ISSUE THREAD

**Issue by gmeixiong** [kshedden/datareader#8]
Column labels within sas files are lost with the Go reader.

**Comment by kshedden** [comment]
I think we do retain the labels, but under the current API there does not seem to be a way to access them (they are a non-exported field of the Colum struct, which in turn is hidden as a non-exported field of the SAS7BDATReader struct). 

I will look into some minor restructuring to expose these things.  It might be a few days before I can look at this though.

**Comment by gmeixiong** [comment]
Thanks for the quick response! This would be much appreciated! I’ll take
another look and can submit a PR if the change does not look too
complicated.

**Comment by gmeixiong** [comment]
I submitted a PR to include ColumnLabels and fixed a bug related to them. Please verify when you have the time.
